"""add fields for meetup

Revision ID: 2fb6ec55051f
Revises: 37f73d8e6963
Create Date: 2014-09-15 02:49:23.106092

"""

# revision identifiers, used by Alembic.
revision = '2fb6ec55051f'
down_revision = '37f73d8e6963'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('eventbrite_disabled', sa.Boolean(), nullable=True))
    op.add_column('calendar', sa.Column('google_disabled', sa.Boolean(), nullable=True))
    op.add_column('calendar', sa.Column('meetup_disabled', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('to_eventbrite', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('to_google', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('to_meetup', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'to_meetup')
    op.drop_column('event', 'to_google')
    op.drop_column('event', 'to_eventbrite')
    op.drop_column('calendar', 'meetup_disabled')
    op.drop_column('calendar', 'google_disabled')
    op.drop_column('calendar', 'eventbrite_disabled')
    ### end Alembic commands ###
