"""add fields for meetup

Revision ID: 2fb6ec55051f
Revises: 37f73d8e6963
Create Date: 2014-09-15 02:49:23.106092

"""

# revision identifiers, used by Alembic.
revision = '2fb6ec55051f'
down_revision = '37f73d8e6963'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_and_meetups')
    op.drop_table('meetup')
    op.add_column('calendar', sa.Column('eventbrite_disabled', sa.Boolean(), nullable=True))
    op.add_column('calendar', sa.Column('google_disabled', sa.Boolean(), nullable=True))
    op.add_column('calendar', sa.Column('meetup_disabled', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('to_eventbrite', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('to_google', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('to_meetup', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'to_meetup')
    op.drop_column('event', 'to_google')
    op.drop_column('event', 'to_eventbrite')
    op.drop_column('calendar', 'meetup_disabled')
    op.drop_column('calendar', 'google_disabled')
    op.drop_column('calendar', 'eventbrite_disabled')
    op.create_table('meetup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('group_urlname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('calendar_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], [u'calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_and_meetups',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('meetup_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['meetup_id'], [u'meetup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], )
    )
    ### end Alembic commands ###
