"""add group id and name

Revision ID: 31d1635c3462
Revises: 2fb6ec55051f
Create Date: 2014-09-15 20:36:13.364806

"""

# revision identifiers, used by Alembic.
revision = '31d1635c3462'
down_revision = '2fb6ec55051f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('meetup_group_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('meetup_group_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'meetup_group_name')
    op.drop_column('user', 'meetup_group_id')
    ### end Alembic commands ###
