"""change meetup setup

Revision ID: 37f73d8e6963
Revises: 3f55cf483795
Create Date: 2014-09-15 02:13:36.654989

"""

# revision identifiers, used by Alembic.
revision = '37f73d8e6963'
down_revision = '3f55cf483795'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'calendar_type')
    op.add_column('user', sa.Column('meetup_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'meetup_url')
    op.add_column('calendar', sa.Column('calendar_type', sa.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
