"""initial commit

Revision ID: 3bddda627f2a
Revises: None
Create Date: 2014-08-27 02:29:16.989391

"""

# revision identifiers, used by Alembic.
revision = '3bddda627f2a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
