"""add meetup table

Revision ID: 3f55cf483795
Revises: None
Create Date: 2014-09-13 03:50:23.863274

"""

# revision identifiers, used by Alembic.
revision = '3f55cf483795'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('group_urlname', sa.String(length=255), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_and_meetups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meetup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_and_meetups')
    op.drop_table('meetup')
    ### end Alembic commands ###
