"""add description field to locations

Revision ID: 44d5f3a06afd
Revises: 208ed1ead94
Create Date: 2014-08-29 01:29:16.210909

"""

# revision identifiers, used by Alembic.
revision = '44d5f3a06afd'
down_revision = '208ed1ead94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'description')
    ### end Alembic commands ###
